image: node:latest

stages:
  - lint
  - build
  - test

cache:
  paths:
    - node_modules/

lint_stage:
  stage: build
  script:
    - npm run lint

build_stage:
  stage: build
  script:
    - npm install
    - npm run build

test_stage:
  stage: test
  script: npm test
