stages:
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

lint_stage:
  image: node:latest-alpine

  stage: lint
  script:
    - npm run lint
  only:
    - merge_requests

test_stage:
  image: node:latest-alpine
  stage: test
  script: npm test
  only:
    - merge_requests

build_stage:
  image: node:latest-alpine
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
      paths:
        - dist/
      expire_in: 2 weeks
  only:
    - master

deploy_staging:
  image: node:latest
  stage: deploy
  script:
    - git remote add heroku_staging https://heroku:$HEROKU_API_KEY@git.heroku.com/node-ci-cd-demo-staging.git
    - git push heroku_staging HEAD:master
    - echo "Deployed to staging server"
  environment:
    name: staging
    url: https://node-ci-cd-demo-staging.herokuapp.com/
  only:
    - staging

deploy_production:
  image: node:latest
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/node-ci-cd-demo.git
    - git push heroku HEAD:master
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://node-ci-cd-demo.herokuapp.com/
  when: manual
  only:
    - master
