image: mhart/alpine-node:latest

stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

lint_stage:
  stage: lint
  script:
    - npm run lint
  only:
    - merge_requests

test_stage:
  stage: test
  script: npm test
  only:
    - merge_requests

build_stage:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
      paths:
        - dist/
      expire_in: 2 weeks
  only:
    - master
